version: '3.8'

services:
  # API Gateway
  api-gateway:
    image: birklauritzen/api-gateway:latest
    ports:
      - "5000:8000"  # Host port 5000 -> Container port 8000
    depends_on:
      - abonnement-service
      - fakturering-service
      - fleet-service
      - kunde-service
      - skade-service

  # Abonnement Service
  abonnement-service:
    image: birklauritzen/abonnement-service:latest
    ports:
      - "5001:5001"

  # Fakturering Service
  fakturering-service:
    image: birklauritzen/fakturering-service:latest
    ports:
      - "5002:5002"

  # Fleet Service
  fleet-service:
    image: birklauritzen/fleet-service:latest
    ports:
      - "5003:5003"

  # Kunde Service
  kunde-service:
    image: birklauritzen/kunde-service:latest
    ports:
      - "5004:5004"

  # Skade Service
  skade-service:
    image: birklauritzen/skade-service:latest
    ports:
      - "5005:5005"