name: Build and deploy container app to Azure Web App - bilabonnement

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Replace with your secret name
        password: ${{ secrets.DOCKER_TOKEN }}     # Replace with your Docker Hub token

    - name: Build and push container image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./api-gateway           # Build context set to api-gateway folder
        file: ./api-gateway/Dockerfile   # Path to Dockerfile inside api-gateway folder
        tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bilabonnement'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f0f5cb34a42a4e92998b06f7fb5792c1 }}
        images: ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.sha }}
